### ISSUE TITLE
Add flythrough animation feature

### ISSUE THREAD

**Issue by andinet** [KitwareMedical/vpaw#9]
We need a flythrough animation feature in VPAW. This is to aid in communicating aspects of a patient’s airway/anatomy to other clinicians. A flythrough path is defined by creating a set of keyframes that store camera poses. The camera poses are interpolated between keyframes to produce smooth camera movement along the camera path.

Task:

A standalone KeyFrameEditor module (or feature added to an existing module) for generating and exporting volume rendering animations. The module will provide a timeline and tracks allowing to save, edit and delete key frames associated with transfer function, ROI clipping box and camera position and orientation.  Available keyframe interpolation functions will include ramp, exponential and bezier. Camera path will be represented by a curve annotation.

The plan is to distribute this feature as a standalone module as a Slicer extension or added to an existing module in Slicer core.

PS

Related modules to explore

1) Sequence module ( https://slicer.readthedocs.io/en/latest/user_guide/modules/sequences.html )
2) ScreenCapture module ( https://slicer.readthedocs.io/en/latest/user_guide/modules/screencapture.html )
3) Endoscope module   ( https://slicer.readthedocs.io/en/latest/user_guide/modules/endoscopy.html)

4) SlicerMorph Animator module  ([Animator:](https://github.com/SlicerMorph/SlicerMorph/tree/master/Docs/Animator)

**Comment by jadh4v** [comment]
See last paragraph in comment here: https://discourse.slicer.org/t/support-for-keyframe-based-animation/6885/6

How should we implement vpaw flythrough? Should it be keyframe interpolation of `camera poses` along a curve, or `features/structures to look-at` as you flythrough.

**Comment by jadh4v** [comment]
Based on our internal discussions and from the [discourse discussion thread](https://discourse.slicer.org/t/upgrading-endoscopy-extension-with-camera-interpolation/23546), we have decided to modify the Endoscopy module to provide full support for a camera flythrough and keyframe interpolation. We can borrow specific implementations from CameraPath as/if needed.

## Keyframe Interpolation
(From Discourse)
- *Add some pure-VTK camera interpolation functionality, perhaps just one class based on [vtkQuaternionInterpolator](https://vtk.org/doc/nightly/html/classvtkQuaternionInterpolator.html#details) with some extra code to handle changes in field of view and maybe other parameters. This could go in vtkAddon if it’s C++ or in Endoscopy logic if it could be done in python (I’d think it could).*

## User Interface
(From Discourse)
- We could use the 3D view camera state itself as a way to insert keyframes. Initially we were considering having a [flight mode](https://github.com/KitwareMedical/Slicer/commit/9af308920309ec8cef890b98078574ef36de3737) for the 3D view to assist in flying around and placing keyframes, but since we can define the path curve first, it is probably not needed. The user can just fly along the path and stop and insert keyframes wherever necessary.

- Regarding display of keyframes we can simply use a camera mesh model to indicate the position or use Plane markups

- Along with camera pos and fov, would it make sense to also interpolate volume property, etc for better local control of visualization?
*The Animator module [has some code for this](https://github.com/SlicerMorph/SlicerMorph/blob/master/Animator/Animator.py#L277-L434) and it would be nice to either reuse or generalize this feature. Currently it requires that the transfer functions have the same number of control points at the keyframes.*

- We should provide headlights that move with the camera (endoscopy simulation).

## Use of Markups
(Discussions with @jcfr)
- Plane markup has controls to work as a camera pose. Can be used as an interaction widget for placing and modifying camera poses along the flythrough curve.
- Explore use of [Dependant markups](https://github.com/DCBIA-OrthoLab/Q3DCExtension/tree/5c2d0369416e578c223b44cecaa727412da68e33/DependantMarkups). It may also be worth looking into Dependant Markups for automatic updating of related markups.

## Nice To Have
(From Discourse)
- *It would also make sense for the Endoscopy module to export to a Sequence, like the Animator does, so that it could be recorded by the ScreenCapture logic.* -- Steve Pieper

**Comment by jadh4v** [comment]
Since we want to upgrade endoscopy and contribute it upstream into core Slicer, I have created a parallel issue / enhancement request in Slicer core here:
https://github.com/Slicer/Slicer/issues/6502
cc: @HarryDC @andinet

**Comment by Leengit** [comment]
I am closing this issue in favor of Issue https://github.com/Slicer/Slicer/issues/6502 under the thinking that the implementation will be within Slicer's Endoscopy module rather than within VPAW.
